name: first app system

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      firstapp:
        image: hassanzahidd/hassan-first-app:latest
        ports:
          - 3001:3000
        volumes:
          - ./:/app
          - /app/node_modules

      db:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install

      - name: Run server in background
        run: |
          nohup node server.js > server.log 2>&1 &

      - name: Check if server is running
        run: |
          sleep 5  # Wait for the server to start
          curl -I http://localhost:3000 || (echo "Server did not start" && exit 1)
