name: Some Name
age: 2
isMale: true
# access: true
# courses:
#   - maths
#   - science
#   - english
#   - urdu
# address:
#   home_address:
#     house_nunber: 123
#   office_address:
#     house_nunber: 456
#     street: 789
name: Docker Build and Push

on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Docker Hub Login
              run: echo "mypassword" |  docker login -u codewithfaraz -password-stdin
